exclude_patterns:
  - config/
  - db/
  - dist/
  - features/
  - '**/node_modules/'
  - script/
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - Tests/
  - '**/vendor/'
  - '**/*_test.go'
  - '**/*.d.ts'
  - '*.config.js'
  - public/
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-66
  reek:
    enabled: true
  flog:
    enabled: true
  bundler-audit:
    enabled: true
  brakeman:
    enabled: true
