---
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Style/CommandLiteral:
  EnforcedStyle: mixed

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces

Layout/LineLength:
  Max: 140
  AutoCorrect: true

Metrics/BlockLength:
  Exclude:
    - test/dummy/db/schema.rb
