addons:
  apt:
    packages:
      - chromium-chromedriver
  chrome: stable
  postgresql: 9.6
  code_climate:
    repo_token: 9136fc9fa7bc99df183ee4fb173f7a424361191785f303954ea0262f896a86df
after_success:
  - bundle exec codeclimate-test-reporter
before_install:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - gem update --system
  - gem install bundler
before_script:
  - bundle exec rails db:setup
language: ruby
