---
dist: xenial
addons:
  apt:
    packages:
      - chromium-chromedriver
      - libvips
      - libvips-dev
  chrome: stable
  postgresql: '9.6'
cache:
  - bundler
  - yarn
services:
  - redis-server
before_install:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - nvm install
  - gem update --system
  - gem install bundler
install:
  - bundle install --jobs=3 --retry=3 --deployment
before_script:
  - bundle exec bin/rails db:setup
language: ruby
