name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update package list
      run: sudo apt-get update
    - name: Install Postgres
      run: |
        sudo apt-get install postgresql libpq-dev
        sudo -u postgres createuser -d -s runner
    - name: Install Chromedriver
      run: |
        sudo apt-get install --only-upgrade google-chrome
        sudo apt-get install chromium-chromedriver
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec yarn
    - name: Prepare database
      run: bundle exec rails db:setup
    - name: Test with Rake
      run: bundle exec rake
