name: Ruby

on: [push]

env:
  LANG: en_GB.UTF-8
  RACK_ENV: test
  RAILS_ENV: test
  RAILS_SERVE_STATIC_FILES: enabled
  PIG_CI_KEY: ${{ secrets.PIG_CI_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Add Chrome repo to APT sources
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
    - name: Update package lists
      run: sudo apt-get update
    - name: Install Postgres
      run: |
        sudo apt-get install postgresql libpq-dev
        sudo -u postgres createuser -d -s runner
    - name: Update Chrome
      run: sudo apt-get install google-chrome-stable
    - name: Install Chromedriver
      run: sudo apt-get install chromium-chromedriver
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Cache Bundler dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Cache Yarn dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install Bundler dependencies
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Install Yarn dependencies
      run: bundle exec yarn
    - name: Prepare database
      run: bundle exec rails db:setup
    - name: Test with Rake
      run: |
        mkdir tmp
        bundle exec rake
