name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update package list
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
    - name: Install Postgres
      run: |
        sudo apt-get install postgresql libpq-dev
        sudo -u postgres createuser -d -s runner
    - name: Install Chromedriver
      run: |
        sudo apt-get install google-chrome-stable
        sudo apt-get install chromium-chromedriver
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec yarn
    - name: Prepare database
      run: bundle exec rails db:setup
    - name: Test with Rake
      run: bundle exec rake
